version: '3.8'

services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: