{
 "title": "System metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_activity_duration_seconds_sum[1m]) / rate(pg_stat_activity_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"transcendence\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}