# Generated by Django 5.1 on 2024-12-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0004_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='nickname',
            field=models.CharField(),
        ),
    ]
