# Generated by Django 5.1 on 2025-01-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=512),
        ),
    ]
