services:
  django:
    platform: ${DOCKER_PLATFORM}
    build:
      context: ../
      dockerfile: ./docker/django/Dockerfile
    container_name: django
    volumes:
      - ../:/workspace
      - ./django/zsh_history:/root/.zsh_history
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - migration
      - redis
    restart: on-failure
    networks:
      - transcendence
    environment:
      - VIRTUAL_HOST=localhost,${HOSTNAME}
      - VIRTUAL_PORT=8000
      - EMAIL_HOST=${EMAIL_HOST:-mailhog}  # Default to mailhog for dev
      - EMAIL_PORT=${EMAIL_PORT:-1025}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-False}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@localhost}

  migration:
    platform: ${DOCKER_PLATFORM}
    build:
      context: ../
      dockerfile: ./docker/django/Dockerfile
    container_name: migration
    volumes:
      - ../:/workspace
    env_file:
      - .env
    depends_on:
      - db
      # db:
        # condition: service_healthy
    networks:
      - transcendence
    environment:
      - EMAIL_HOST=${EMAIL_HOST:-mailhog}  # Default to mailhog for dev
      - EMAIL_PORT=${EMAIL_PORT:-1025}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-False}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@localhost}
    command: >
      sh -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py testusers &&
      python manage.py create_superuser &&
      python manage.py collectstatic --clear --noinput
      "

  db:
    platform: ${DOCKER_PLATFORM}
    image: postgres:13
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: on-failure
    environment:
      - TZ=Europe/Paris
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    platform: ${DOCKER_PLATFORM}
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - transcendence

  nginx:
    platform: ${DOCKER_PLATFORM}
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8081:443"
    volumes:
      - ${DOCKER_SOCK}:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
    environment:
      - HTTPS_METHOD=redirect
      - DEFAULT_SSL_CERT=/etc/nginx/certs/localhost.crt
      - DEFAULT_SSL_KEY=/etc/nginx/certs/localhost.key
    restart: on-failure
    networks:
      - transcendence

  mailhog:
    platform: ${DOCKER_PLATFORM}
    image: richarvey/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - transcendence
    environment:
      - VIRTUAL_HOST=mailhog.localhost,mailhog.${HOSTNAME}
      - VIRTUAL_PORT=8025

  # prometheus:
  #   platform: ${DOCKER_PLATFORM}
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   user: root
  #   volumes:
  #     - prometheus_data:/prometheus
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
  #   ports:
  #     - "9090:9090"
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #     - "--storage.tsdb.retention.time=30d"
  #   restart: on-failure
  #   networks:
  #     - transcendence
  #   environment:
  #     - VIRTUAL_HOST=prometheus.localhost,prometheus.${HOSTNAME}
  #     - VIRTUAL_PORT=9090

  # grafana:
  #   platform: ${DOCKER_PLATFORM}
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   user: root
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - prometheus
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
  #     - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
  #     - ./grafana/metrics-dashboard.json:/var/lib/grafana/dashboards/metrics-dashboard.json
  #   restart: on-failure
  #   networks:
  #     - transcendence
  #   environment:
  #     - VIRTUAL_HOST=grafana.localhost,grafana.${HOSTNAME}
  #     - VIRTUAL_PORT=3000

  # node_exporter:
  #   platform: ${DOCKER_PLATFORM}
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   ports:
  #     - "9101:9100"
  #   restart: on-failure
  #   networks:
  #     - transcendence
  #   environment:
  #     - VIRTUAL_HOST=node-exporter.localhost,node-exporter.${HOSTNAME}
  #     - VIRTUAL_PORT=9100

  # postgres_exporter:
  #   platform: ${DOCKER_PLATFORM}
  #   image: prometheuscommunity/postgres-exporter:latest
  #   container_name: postgres-exporter
  #   env_file:
  #     - .env
  #   ports:
  #     - "9187:9187"
  #   depends_on:
  #     - db
  #   restart: on-failure
  #   networks:
  #     - transcendence
  #   environment:
  #     - VIRTUAL_HOST=postgres-exporter.localhost,postgres-exporter.${HOSTNAME}
  #     - VIRTUAL_PORT=9187

  # elasticsearch:
  #   platform: ${DOCKER_PLATFORM}
  #   build:
  #     context: ../
  #     dockerfile: ./docker/elasticsearch/Dockerfile
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #     - xpack.security.enabled=true
  #     - xpack.security.http.ssl.enabled=true
  #     - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/elasticsearch.key
  #     - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/elasticsearch.crt
  #     - ELASTIC_USERNAME=${ELASTIC_USER}
  #     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
  #     - node.max_local_storage_nodes=2
  #     - VIRTUAL_HOST=elasticsearch.localhost,elasticsearch.${HOSTNAME}
  #     - VIRTUAL_PORT=9200
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data
  #     - ./elasticsearch/snapshots:/usr/share/elasticsearch/snapshots
  #   ports:
  #     - "9200:9200"
  #   restart: on-failure
  #   networks:
  #     - transcendence

  # logstash:
  #   platform: ${DOCKER_PLATFORM}
  #   build:
  #     context: ../
  #     dockerfile: ./docker/logstash/Dockerfile
  #   user: root
  #   container_name: logstash
  #   volumes:
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   depends_on:
  #     - elasticsearch
  #   restart: on-failure
  #   networks:
  #     - transcendence
  #   environment:
  #     - xpack.monitoring.enabled=true
  #     - xpack.monitoring.elasticsearch.hosts=["https://elasticsearch:9200"]
  #     - xpack.monitoring.elasticsearch.ssl.certificate_authority=/usr/share/logstash/config/certs/elasticsearch.crt
  #     - xpack.monitoring.elasticsearch.ssl.vertification_mode=none
  #     - xpack.monitoring.elasticsearch.username=${ELASTIC_USER}
  #     - xpack.monitoring.elasticsearch.password=${ELASTIC_PASSWORD}

  # kibana:
  #   platform: ${DOCKER_PLATFORM}
  #   build:
  #     context: ../
  #     dockerfile: ./docker/kibana/Dockerfile
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  #   restart: on-failure
  #   networks:
  #     - transcendence
  #   environment:
  #     - ELASTICSEARCH_URL=https://elasticsearch:9200
  #     - ELASTICSEARCH_HOSTS=["https://elasticsearch:9200"]
  #     - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/localhost.crt
  #     - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
  #     - ELASTICSEARCH_USERNAME=${ELASTIC_USER}
  #     - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
  #     - SERVER_SSL_ENABLED=true
  #     - SERVER_SSL_KEY=/usr/share/kibana/config/certs/localhost.key
  #     - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/localhost.crt
  #     - VIRTUAL_HOST=kibana.localhost,kibana.${HOSTNAME}
  #     - VIRTUAL_PORT=5601

  # filebeat:
  #   platform: ${DOCKER_PLATFORM}
  #   build:
  #     context: ../
  #     dockerfile: ./docker/filebeat/Dockerfile
  #   container_name: filebeat
  #   user: root
  #   volumes:
  #     - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - filebeat_data:/var/log
  #   depends_on:
  #     - logstash
  #   restart: on-failure
  #   networks:
  #     - transcendence

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data
  # grafana_data:
  #   name: grafana_data
  # prometheus_data:
  #   name: prometheus_data
  # es_data:
  #   name: es_data
  # filebeat_data:
  #   name: filebeat_data
