services:
  django:
    build:
      context: ../
      dockerfile: ./docker/django/Dockerfile
    container_name: django
    volumes:
      - ../:/workspace
      - ./django/zsh_history:/root/.zsh_history

    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
    restart: on-failure

  grafana:
    image: grafana/grafana:latest
    user: root
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/metrics-dashboard.json:/var/lib/grafana/dashboards/metrics-dashboard.json
      # - ./grafana/certs/:/etc/grafana/certs/
    restart: on-failure

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9101:9100"
    restart: on-failure

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    env_file:
      - .env
    ports:
      - "9187:9187"
    depends_on:
      - db
    restart: on-failure

  # nginx:
  #   image: nginx:latest
  #   user: nginx
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/certs:/etc/nginx/certs
  #   ports:
  #     - "4443:443"
  #   depends_on:
  #     - django
  #     - prometheus
  #     - grafana
  #     - node_exporter
  #     - postgres_exporter
  #   restart: on-failure

  nginx:
    build:
      context: ../docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "4443:443"
    depends_on:
      - django
      - prometheus
      - grafana
      - node_exporter
      - postgres_exporter
    restart: on-failure

volumes:
  postgres_data:
  grafana_data:
  prometheus_data: