# Generated by Django 5.1 on 2025-01-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_player1_guest', to='tournament.guest'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_player2_guest', to='tournament.guest'),
        ),
    ]
