# Generated by Django 5.1 on 2024-11-14 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='win_treshold',
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
