# Generated by Django 5.1 on 2024-11-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_game_id_gameplayer_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='display_name',
            new_name='alias',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ONGOING', 'Ongoing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('DISCONNECTED', 'Disconnected'), ('ELIMINATED', 'Eliminated')], default='IDLE', max_length=20),
        ),
    ]
