# Generated by Django 5.1 on 2024-11-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_display_name_gameplayer_alias_game_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='level',
            field=models.CharField(choices=[('TABLETENNIS', 'Table Tennis'), ('FOOTBALL', 'Football'), ('TENNIS', 'Tennis'), ('CLASSIC', 'Classic')], default='CLASSIC', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='powerup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='time_played',
            field=models.IntegerField(default=0),
        ),
    ]
