# Generated by Django 5.1 on 2024-12-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
