# Generated by Django 5.1 on 2024-12-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_delete_message'),
        ('game', '0011_message'),
    ]

    operations = [
    ]
