# Generated by Django 5.1 on 2024-12-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_merge_0009_delete_message_0011_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'easy'), ('MEDIUM', 'medium'), ('HARD', 'hard')], default='EASY', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='level',
            field=models.CharField(choices=[('TABLETENNIS', 'tableTennis'), ('FOOTBALL', 'football'), ('TENNIS', 'tennis'), ('CLASSIC', 'classicPong')], default='CLASSIC', max_length=20),
        ),
    ]
