<<<<<<<< HEAD:srcs/backend/game/migrations/0014_alter_game_difficulty_alter_game_level.py
# Generated by Django 5.1 on 2025-01-21 16:00
========
# Generated by Django 5.1 on 2025-01-21 16:23
>>>>>>>> ad528c0 (completed merge, fixed migrations):srcs/backend/game/migrations/0015_alter_game_difficulty_alter_game_level.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:srcs/backend/game/migrations/0014_alter_game_difficulty_alter_game_level.py
        ('game', '0013_game_username_one_game_username_two'),
========
        ('game', '0014_alter_game_difficulty_alter_game_level'),
>>>>>>>> ad528c0 (completed merge, fixed migrations):srcs/backend/game/migrations/0015_alter_game_difficulty_alter_game_level.py
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='level',
            field=models.CharField(choices=[('TABLETENNIS', 'Table Tennis'), ('FOOTBALL', 'Football'), ('TENNIS', 'Tennis'), ('CLASSIC', 'Classic')], default='CLASSIC', max_length=20),
        ),
    ]
