# Generated by Django 5.1 on 2024-12-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_game_difficulty_alter_game_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='username_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='username_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
