# Generated by Django 5.1 on 2024-12-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_game_username_one_game_username_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='EASY', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='level',
            field=models.CharField(choices=[('tableTennis', 'Table Tennis'), ('football', 'Football'), ('tennis', 'Tennis'), ('classicPong', 'Classic')], default='CLASSIC', max_length=20),
        ),
    ]
