# Generated by Django 5.1 on 2024-11-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_password',
            new_name='new_password',
        ),
    ]
