# Generated by Django 5.1 on 2024-11-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_password',
            field=models.CharField(blank=True, null=True, verbose_name='old password'),
        ),
    ]
