# Generated by Django 5.1 on 2024-11-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_new_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/default-avatar.jpg', upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
