# Generated by Django 5.1 on 2024-12-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_42_user',
            field=models.BooleanField(default=False),
        ),
    ]
