# Generated by Django 5.1 on 2024-12-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_42_user'),
        ('user', '0007_user_last_activity'),
    ]

    operations = [
    ]
