# Generated by Django 5.1 on 2025-01-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
