# Generated by Django 5.1 on 2025-01-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_blocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
