# Generated by Django 5.1 on 2025-01-24 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='open', max_length=50)),
                ('winner', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('player_count', models.IntegerField(default=0)),
                ('current_match', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('player1_name', models.CharField(default='Player 1', max_length=150)),
                ('player2_name', models.CharField(default='Player 2', max_length=150)),
            ],
        ),
    ]
