# Generated by Django 5.1 on 2025-01-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='name',
        ),
    ]
