# Generated by Django 5.1 on 2024-12-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(default='upcoming', max_length=20),
        ),
    ]
